### ISSUE TITLE
Determine how to cut releases

### ISSUE THREAD

**Issue by flipactual** [emdaer/emdaer#3]
I would rather handle this with travis than do it locally

**Comment by infiniteluke** [comment]
@thebruce can this be closed with #24 merged?

**Comment by infiniteluke** [comment]
This is mostly resolved. However, package versions aren't in sync... It would be a good thing to provide since there's now a v1.1.0 release but @emdaer/core, for example, is not published at v1.1.0.

If it can be done, it's just by passing a flag to lerna or specifying something in the config. If it is harder that that, we could deprioritize this.

HT @flipactual for above comments

**Comment by infiniteluke** [comment]
https://github.com/lerna/lerna#fixedlocked-mode-default
