### ISSUE TITLE
Files should always write to the proper destination

### ISSUE THREAD

**Issue by flipactual** [emdaer/emdaer#72]

**Comment by infiniteluke** [comment]
I can't reproduce this consistently but did see it once.
Here's what I tried.
```sh
git pull origin master
yarn; make bootstrap
yarn emdaer
```

I think it may be this:
```js
.map(async (readme, index) => {
        const [, fileName, fileExtension] = origins[index].match(
          /\.emdaer\/(.*)\.emdaer(\.md)/
        );
	...
})
```

mapping, then relying on the `index` to get the file name, but then using the `readme` later when writing doesn't seem reliable since I don't think map ensures order. Maybe `forEach` would be better here? Initial perf looks to be the same.

**Comment by flipactual** [comment]
I would consider changing what you're mapping

1. get the initial thing
2. map it to an object containing it and more things
3. pass that on

Referencing back to `origins` and using and index for lookup is stateful
