### ISSUE TITLE
Syntax highlighting in code blocks is not working

### ISSUE THREAD

**Issue by e0ipso** [emdaer/emdaer#87]
- `emdaer` version: 2.0.0
- `transform-prettier` version (multiple if relevant): 2.0.0
- `node` version: 8.9.1
- `npm` (or `yarn`) version: yarn 1.3.2

Contents of your *.emdaer.md file:

https://raw.githubusercontent.com/e0ipso/cache-tags/master/.emdaer/README.emdaer.md

What you did:

I added a code block with js highlighting.

What happened:

![2018-03-30 08-25-52](https://user-images.githubusercontent.com/1140906/38126931-fc4d668e-33f3-11e8-900a-14a22622422c.png)

Reproduction repository:

https://github.com/e0ipso/cache-tags

**Comment by infiniteluke** [comment]
I just experienced this as well. This is due to the way https://github.com/markedjs/marked translates a code block to html. There is a fix for this, but it requires a change to emdaer core. Will update this issue when I have something.

**Comment by infiniteluke** [comment]
This issue is particular to code blocks. marked, used in emdaer core to transform md to html, has an opinion on how to convert md for a code fence + language into html + classes that denote syntax highlighting. The issue with this is that different platforms (GitHub, bitbucket, even md previewers in IDEs) all have different opinions on this as well. Supporting that would be a nightmare.

Instead I think we should punt on the problem all together and let different platforms handle that.

We could do this in a few ways:
1. Remove marked/html-minifier dependencies from core and output md for all of emdaer. No more HTML.
2. Add an `outputFormat` flag to the CLI which allows md or html. If folks run into issues with html, they can switch. This adds things that emdaer does. Maybe that's good?
3. Hacky: Override the marked `code` renderer to output md code fences instead of html. (this would require removing html-minifier since the output of marked would no longer be pure html anymore). This essentially allows emdaer to "ignore" code fences.
4. Do not support syntax highlighting. Syntax highlighted code blocks are fundamental to readmes. I don't like this option.

**Comment by e0ipso** [comment]
Maybe a new plugin to inject unprocessed Markdown files? The I could move the code blocks to their own `*.md` and require them in the main doc. It feels a wonky DX though.

**Comment by infiniteluke** [comment]
That seems like a work around. I'd like us to fix the issue. Users should be able to write code in their *.emdaer.md file like any other md file. Asking them to do something special for code fences seems less than ideal.

I'm leaning towards `1.` at the moment. I'm not remembering the advantage to rendering to HTML. @flipactual will remember why that was added.

**Comment by flipactual** [comment]
There are a lot of reasons not to output to markdown, but they can best be summed up in two points: 
1. Markdown is a nightmare to parse which causes unexpected interpretation by various platforms
2. HTML provides many elements which are supported by platforms including GitHub, NPM, etc. and are not possible with Markdown... using these in primarily Markdown files is fine until it exacerbates the previous issue

I understand the desire to have syntax highlighting in code blocks. GitHub (et al) put us all in a difficult position by requiring us to write in two or more languages to utilize all the features of their README processing – there can't be a clean fix until they put more effort into the platform

Altering default behavior could regress our ability to do useful things such as
```md
<details>
  <code>
    true
  </code>
</details>
```

I'm tempted to say that any Markdown code block with a language specified should commented out until all other operations on the file are complete at which point we would uncomment the block

**Comment by infiniteluke** [comment]
> HTML provides many elements which are supported by platforms including GitHub, NPM, etc. and are not possible with Markdown

This is a really great point. Thanks for clarifying this. There is also an argument to be made that we can have both. Because emdaer's plugins output HTML we can control that side of things. Also, there is nothing that keeps people authoring readmes from writing HTML themselves. But transforming md to html would still help with portability and consistency across platforms.

I'm cool with your proposed solution. `3.` from https://github.com/emdaer/emdaer/issues/87#issuecomment-377829411 would work too. Thoughts on that?

**Comment by flipactual** [comment]
I would rather keep existing functionality like minification if we can

**Comment by e0ipso** [comment]
Great to hear that there is a path forward!

Thanks for the fantastic work being done here.

**Comment by infiniteluke** [comment]
#88 is my proposed fix for this.

**Comment by infiniteluke** [comment]
`yarn upgrade --pattern @emdaer` to get these changes. Thanks for reporting this @e0ipso!
